"""Into 'accounts' added 'first_name', 'last_name', 'avatar'

Revision ID: 5233e4e0edd0
Revises: c922bc4d287e
Create Date: 2021-09-25 01:11:30.592314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233e4e0edd0'
down_revision = 'c922bc4d287e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'avatar')
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###
